
import React, { useEffect, useRef, useState } from 'react';
import { DifficultyConfig } from '../constants';

interface SettlementPosterProps {
  score: number;
  onClose: () => void;
  difficulty: DifficultyConfig;
  imagePool: string[];
}

const SettlementPoster: React.FC<SettlementPosterProps> = ({ score, onClose, difficulty, imagePool }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [posterUrl, setPosterUrl] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);

  // 指定的居中展示图片
  const FIXED_IMAGE_URL = 'https://i0.hdslb.com/bfs/openplatform/d447367816c734f5f94be8fc27b09fcaa854aaff.png';

  useEffect(() => {
    const generatePoster = async () => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      // 海报尺寸 750x1200
      canvas.width = 750;
      canvas.height = 1200;

      // 1. 背景绘制
      const grad = ctx.createLinearGradient(0, 0, 0, canvas.height);
      grad.addColorStop(0, '#0a0d17');
      grad.addColorStop(0.5, '#1e293b');
      grad.addColorStop(1, '#0f172a');
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // 2. 边框 (外框 30, 内线 55)
      ctx.strokeStyle = '#b4975a';
      ctx.lineWidth = 20;
      ctx.strokeRect(30, 30, canvas.width - 60, canvas.height - 60);
      ctx.lineWidth = 2;
      ctx.strokeRect(55, 55, canvas.width - 110, canvas.height - 110);

      // 3. 标题
      ctx.textAlign = 'center';
      ctx.fillStyle = '#fde047';
      ctx.font = 'bold 50px "Cinzel", serif';
      ctx.fillText('迦勒底战绩报告', canvas.width / 2, 140);
      
      ctx.fillStyle = '#64748b';
      ctx.font = '24px "Noto Sans SC", sans-serif';
      ctx.letterSpacing = '4px';
      ctx.fillText('CHALDEA LOGIC RECORD', canvas.width / 2, 180);

      // 4. 难度等级显示
      ctx.fillStyle = '#ffffff';
      ctx.font = '28px "Noto Sans SC", sans-serif';
      ctx.fillText(`[ ${difficulty.label} ]`, canvas.width / 2, 260);

      // 5. 分数大字显示 (上方)
      const scoreText = score.toLocaleString();
      ctx.fillStyle = '#fbbf24';
      ctx.font = 'bold 120px "Courier New", monospace';
      ctx.shadowBlur = 15;
      ctx.shadowColor = 'rgba(251, 191, 36, 0.5)';
      ctx.fillText(scoreText, canvas.width / 2, 400);
      ctx.shadowBlur = 0;

      // 6. 分享文案 (手动分行，确保分值在第二行)
      ctx.fillStyle = '#e2e8f0';
      ctx.font = 'bold 36px "Noto Sans SC", sans-serif';
      
      const line1 = "我在武内脸消消乐中获得了";
      const line2 = `${scoreText} 分的好成绩！`;
      const line3 = "快分享给你的迦人们吧！";

      ctx.fillText(line1, canvas.width / 2, 510);
      ctx.fillText(line2, canvas.width / 2, 575); // 分数在第二行

      ctx.fillStyle = '#94a3b8';
      ctx.font = '30px "Noto Sans SC", sans-serif';
      ctx.fillText(line3, canvas.width / 2, 645);

      // 7. 展示图片绘制 (居中单张大图)
      const drawServant = (src: string, x: number, y: number, width: number, height: number) => {
        return new Promise<void>((resolve) => {
          const img = new Image();
          img.crossOrigin = "anonymous";
          img.onload = () => {
            ctx.save();
            ctx.beginPath();
            const radius = 20;
            ctx.moveTo(x + radius, y);
            ctx.arcTo(x + width, y, x + width, y + height, radius);
            ctx.arcTo(x + width, y + height, x, y + height, radius);
            ctx.arcTo(x, y + height, x, y, radius);
            ctx.arcTo(x, y, x + width, y, radius);
            ctx.closePath();
            ctx.clip();
            ctx.drawImage(img, x, y, width, height);
            ctx.restore();
            
            ctx.strokeStyle = '#b4975a';
            ctx.lineWidth = 4;
            ctx.strokeRect(x, y, width, height);
            resolve();
          };
          img.onerror = () => {
            console.warn("Poster image failed to load:", src);
            resolve();
          };
          img.src = src;
        });
      };

      const sWidth = 430;
      const sHeight = 430;
      const startX = (canvas.width - sWidth) / 2;
      const startY = 700; 

      await drawServant(FIXED_IMAGE_URL, startX, startY, sWidth, sHeight);

      // 8. 页脚署名
      ctx.fillStyle = '#475569';
      ctx.font = '18px "Noto Sans SC", sans-serif';
      ctx.fillText('Generated by 阿良良睦历', canvas.width / 2, 1155);

      setPosterUrl(canvas.toDataURL('image/png'));
      setIsLoading(false);
    };

    generatePoster();
  }, [score, difficulty]);

  return (
    <div className="flex flex-col items-center w-full max-w-lg animate-in fade-in zoom-in duration-500">
      <div className="relative w-full aspect-[750/1200] max-h-[70vh] overflow-hidden rounded-xl shadow-[0_20px_50px_rgba(0,0,0,0.5)] gold-border bg-slate-900 group">
        {isLoading && (
          <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/80 backdrop-blur-sm z-10">
            <div className="w-14 h-14 border-4 border-yellow-500 border-t-transparent rounded-full animate-spin mb-4"></div>
            <p className="text-yellow-500 font-bold tracking-widest text-lg animate-pulse">正在生成战报...</p>
          </div>
        )}
        {posterUrl && (
          <>
            <img src={posterUrl} alt="Achievement Poster" className="w-full h-full object-contain" />
            <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center pointer-events-none">
               <span className="text-white bg-black/60 px-4 py-2 rounded-full text-sm">长按图片保存</span>
            </div>
          </>
        )}
      </div>
      
      <div className="flex gap-4 mt-8 w-full">
        <button 
          onClick={onClose}
          className="flex-1 px-6 py-4 bg-slate-800 border border-slate-600 rounded-xl font-bold hover:bg-slate-700 transition-colors text-slate-300"
        >
          返回大厅
        </button>
        <a 
          href={posterUrl} 
          download={`武内脸消消乐战报_${score}.png`} 
          rel="noreferrer"
          className="flex-[2] px-6 py-4 bg-gradient-to-r from-yellow-600 to-yellow-800 rounded-xl font-bold text-center border-b-4 border-yellow-900 shadow-lg active:translate-y-1 active:border-b-0 transition-all flex items-center justify-center gap-2"
        >
          <i className="fa-solid fa-cloud-arrow-down"></i> 保存荣誉战报
        </a>
      </div>
      
      <canvas ref={canvasRef} className="hidden" />
    </div>
  );
};

export default SettlementPoster;